language: node_js

sudo: false

node_js:
  - "8"
  - "9"
  - "10"

branches:
  only:
    - master

cache:
  directories:
    - node_modules
  
addons:
  chrome: stable

notifications:
  email:
    recipients:
      - marcio.hsdl@gmail.com
    on_success: always
    on_failure: always

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod
